AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ascending-order

  Sample SAM Template for ascending-order

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AscendingOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ascending_order/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        AscendingOrder:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ascending-order
            Method: get
            RequestParameters:
              - method.request.querystring.numbers:
                 Required: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AscendingOrderApi:
    Description: "API Gateway endpoint URL for Prod stage for ascending order function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ascending-order/"
  AscendingOrderFunction:
    Description: "ascending order Lambda Function ARN"
    Value: !GetAtt AscendingOrderFunction.Arn
  AscendingOrderFunctionIamRole:
    Description: "Implicit IAM Role created for ascending order function"
    Value: !GetAtt AscendingOrderFunctionRole.Arn
